/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DTO.TenisDTO;
import DAL.TenisDAL;
/**
 *
 * @author arrascaeto
 */
public class FrmCadastroTenis extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCadastroTenis.class.getName());

    /**
     * Creates new form FrmCadastroTenis
     */
    public FrmCadastroTenis() {
    initComponents();

    setIconImage(new javax.swing.ImageIcon(
            getClass().getResource("/imagens/iconetenis.png")
    ).getImage());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtFabricante = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new UI.PainelImagem();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 45, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Fabricante:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 79, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Modelo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 113, -1, -1));

        txtID.addActionListener(this::txtIDActionPerformed);
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 42, 180, -1));

        txtFabricante.addActionListener(this::txtFabricanteActionPerformed);
        getContentPane().add(txtFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 76, 180, -1));

        txtModelo.addActionListener(this::txtModeloActionPerformed);
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 110, 180, -1));

        bntSalvar.setText("SALVAR");
        bntSalvar.addActionListener(this::bntSalvarActionPerformed);
        getContentPane().add(bntSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 176, -1, -1));

        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 176, -1, -1));

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 176, -1, -1));

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 176, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 68, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconetenis.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel6)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFabricanteActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    int id = Integer.parseInt(txtID.getText());

    TenisDAL dal = new TenisDAL();
    dal.excluir(id);

    javax.swing.JOptionPane.showMessageDialog(null, "Tênis excluído com sucesso!");

    txtID.setText("");
    txtFabricante.setText("");
    txtModelo.setText("");
txtFabricante.requestFocus();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
    TenisDTO dto = new TenisDTO();

dto.setTenFabricante(txtFabricante.getText());
dto.setTenModelo(txtModelo.getText());

TenisDAL dal = new TenisDAL();

dal.cadastrar(dto);

javax.swing.JOptionPane.showMessageDialog(this,
        "Tênis cadastrado com sucesso!");

txtFabricante.setText("");
txtModelo.setText("");
txtFabricante.requestFocus();
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

    txtID.setText("");
    txtFabricante.setText("");
    txtModelo.setText("");

    txtFabricante.requestFocus();

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
 TenisDTO dto = new TenisDTO();

    dto.setTenID(Integer.parseInt(txtID.getText()));
    dto.setTenFabricante(txtFabricante.getText());
    dto.setTenModelo(txtModelo.getText());

    TenisDAL dal = new TenisDAL();
    dal.alterar(dto);

    javax.swing.JOptionPane.showMessageDialog(null, "Tênis alterado com sucesso!");      
    }//GEN-LAST:event_btnAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalvar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
